config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see
  get 'batters/salary(/:salary)', to: 'batters#show'
  get 'pitchers/salary(/:salary)', to: 'pitchers#show'

  resources :batters
  resources :pitchers
  get 'pitchers/salary/:salary', to: 'pitchers#show_by_salary'



  get 'search', to: 'search#index'
  post 'search', to: 'search#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/batter.rb
class Batter < ApplicationRecord
end

app/models/pitcher.rb
class Pitcher < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
    def regex_is_number? string
    no_commas =  string.gsub(',', '')
    matches = no_commas.match(/-?\d+(?:\.\d+)?/)
    if !matches.nil? && matches.size == 1 && matches[0] == no_commas
      true
    else
      false
    end
  end
end

app/controllers/batters_controller.rb
class BattersController < ApplicationController
  before_action :set_batter, only: [:edit, :update, :destroy]

  # GET /batters
  # GET /batters.json
  def index
    @batters = Batter.limit(100)
    if params[:salary]
      show
    end
  end

  # GET /batters/1
  # GET /batters/1.json
  def show
    #TODO: copypasta from batters, should figure out how to share code
    # Feels like show and search shouldn't be munged together like this
    # also using "salary" in place of generalized search term
    if params[:salary]
      search = params[:salary]

      if regex_is_number? search
        @batters = Batter.where(salary:search.gsub(",","").to_i).distinct
      else
        # note this currently requires EXACT match of last name, should improve it
        @batters = Batter.where(lname:search).order(:season, salary: :desc)
      end
      if @batters.count == 1
        @batter = @batters.first
      else
        @salaryForm = true
        render :index
      end

    elsif params[:id]
      set_batter
    end
  end



  # GET /batters/new
  def new
    @batter = Batter.new
  end

  # GET /batters/1/edit
  def edit
  end

  # POST /batters
  # POST /batters.json
  def create
    @batter = Batter.new(batter_params)

    respond_to do |format|
      if @batter.save
        format.html { redirect_to @batter, notice: 'Batter was successfully created.' }
        format.json { render :show, status: :created, location: @batter }
      else
        format.html { render :new }
        format.json { render json: @batter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /batters/1
  # PATCH/PUT /batters/1.json
  def update
    respond_to do |format|
      if @batter.update(batter_params)
        format.html { redirect_to @batter, notice: 'Batter was successfully updated.' }
        format.json { render :show, status: :ok, location: @batter }
      else
        format.html { render :edit }
        format.json { render json: @batter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /batters/1
  # DELETE /batters/1.json
  def destroy
    @batter.destroy
    respond_to do |format|
      format.html { redirect_to batters_url, notice: 'Batter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_batter
      @batter = Batter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def batter_params
      params.fetch(:batter, {})
    end
end

app/controllers/pitchers_controller.rb
class PitchersController < ApplicationController
  before_action :set_pitcher, only: [:edit, :update, :destroy]

  # GET /pitchers
  # GET /pitchers.json
  def index
    @pitchers = Pitcher.limit(100)
    if params[:salary]
      show
    end
  end

  # GET /pitchers/1
  # GET /pitchers/1.json
  def show
    #TODO: copypasta from batters, should figure out how to share code
    # Feels like show and search shouldn't be munged together like this
    # also using "salary" in place of generalized search term
    if params[:salary]
      search = params[:salary]

      if regex_is_number? search
        @pitchers = Pitcher.where(salary:search.gsub(",","").to_i).distinct
      else
        # note this currently requires EXACT match of last name, should improve it
        @pitchers = Pitcher.where(lname:search).order(:season, salary: :desc)
      end
      if @pitchers.count == 1
        @pitcher = @pitchers.first
      else
        @salaryForm = true
        render :index
      end

    elsif params[:id]
      set_pitcher
    end
  end


  # # GET /pitchers/salary/xxxxxxx
  # def show_by_salary
  #   #TODO: copypasta from batters, should figure out how to share code
  #   @pitchers = Pitcher.where(salary:params[:salary].gsub(",","").to_i).distinct
  #   if @pitchers.count == 1
  #     @pitcher = @pitchers.first
  #     render :show
  #   else
  #     @salaryForm = true
  #     render :index
  #   end
  # end


  # GET /pitchers/new
  def new
    @pitcher = Pitcher.new
  end

  # GET /pitchers/1/edit
  def edit
  end

  # POST /pitchers
  # POST /pitchers.json
  def create
    @pitcher = Pitcher.new(pitcher_params)

    respond_to do |format|
      if @pitcher.save
        format.html { redirect_to @pitcher, notice: 'Pitcher was successfully created.' }
        format.json { render :show, status: :created, location: @pitcher }
      else
        format.html { render :new }
        format.json { render json: @pitcher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pitchers/1
  # PATCH/PUT /pitchers/1.json
  def update
    respond_to do |format|
      if @pitcher.update(pitcher_params)
        format.html { redirect_to @pitcher, notice: 'Pitcher was successfully updated.' }
        format.json { render :show, status: :ok, location: @pitcher }
      else
        format.html { render :edit }
        format.json { render json: @pitcher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pitchers/1
  # DELETE /pitchers/1.json
  def destroy
    @pitcher.destroy
    respond_to do |format|
      format.html { redirect_to pitchers_url, notice: 'Pitcher was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pitcher
      @pitcher = Pitcher.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pitcher_params
      params.fetch(:pitcher, {})
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
  end

  def search
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/batters_helper.rb
module BattersHelper
end

app/helpers/pitchers_helper.rb
module PitchersHelper
  def pitches_per_inning (pitcher)
    # BFIP = whip+3
    # BBIP = BB9 /9
    # KIP =K9/9
    bfip = pitcher.whip + 3
    # bbip = pitcher.bb_norm.to_f/9
    # kip = pitcher.k9_norm.to_f/9
    bbip = pitcher.bb.to_f/pitcher.ip_162
    kip = pitcher.k.to_f/pitcher.ip_162
    pitches_per_inn = (bfip * 3.392) + (bbip * 4.444) + (kip * 1.916)
    pitches_per_inn.round(2)
  end
  def pitches_max(pitcher)
    pitches_per_inn = pitches_per_inning (pitcher)
    pitches_max = pitches_per_inn * pitcher.ip_162
    pitches_max.round(2)
  end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/batters/_form.html.erb
<%= form_with(model: batter, local: true) do |form| %>
  <% if batter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(batter.errors.count, "error") %> prohibited this batter from being saved:</h2>

      <ul>
      <% batter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/batters/edit.html.erb
<h1>Editing Batter</h1>

<%= render 'form', batter: @batter %>

<%= link_to 'Show', @batter %> |
<%= link_to 'Back', batters_path %>

app/views/batters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Batters</h1>

<%= form_tag(batters_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :salary, params[:salary], placeholder: "Salary" %>
    <%= submit_tag "Search by Salary", :name => nil %>
<% end %>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @batters.each do |batter| %>
      <tr>
        <td><%= link_to batter.fname + " " + batter.lname, batter %> (<%=batter.season %> <%= batter.franchise %>) - <%= batter.pa_162 %> PA/162</td>

        <!-- <td><%= link_to 'Edit', edit_batter_path(batter) %></td>
        <td><%= link_to 'Destroy', batter, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/batters/new.html.erb
<h1>New Batter</h1>

<%= render 'form', batter: @batter %>

<%= link_to 'Back', batters_path %>

app/views/batters/show.html.erb
<p id="notice"><%= notice %></p>

  <h1><div class=""><%= @batter.position %></div><%= @batter.fname %> <%= @batter.lname %> (<%= @batter.season %>)</h1>

  <p><%= @batter.franchise %> bats: <%= @batter.bats %>, throws: <%= @batter.throws %></p>

  <div class="card text-white bg-primary mb-3" style="max-width: 20rem;">
  <div class="card-header">Batting Average</div>
  <div class="card-body">
    <h4 class="card-title"><%= @batter.ba %></h4>
    <p class="card-text">AVG </p>
  </div>
</div>

  <% @batter.attributes.each do |name, value| %>
       <%= name %>: <%= value %><br />
  <% end %>

<p>
<%= link_to 'Edit', edit_batter_path(@batter) %> |
<%= link_to 'Back', batters_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BaseballHelper</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="/">SimLeague Baseball Helper</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor01">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= batters_url %>">Batters</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= pitchers_url %>">Pitchers</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">About</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search">
      <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pitchers/_form.html.erb
<%= form_with(model: pitcher, local: true) do |form| %>
  <% if pitcher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pitcher.errors.count, "error") %> prohibited this pitcher from being saved:</h2>

      <ul>
      <% pitcher.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pitchers/edit.html.erb
<h1>Editing Pitcher</h1>

<%= render 'form', pitcher: @pitcher %>

<%= link_to 'Show', @pitcher %> |
<%= link_to 'Back', pitchers_path %>

app/views/pitchers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pitchers</h1>

<%= form_tag(pitchers_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :salary, params[:salary], placeholder: "Salary" %>
    <%= submit_tag "Search by Salary", :name => nil %>
<% end %>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pitchers.each do |pitcher| %>
      <tr>
        <td><%= link_to pitcher.fname + " " + pitcher.lname, pitcher %> (<%=pitcher.season %> <%= pitcher.franchise %>) - <%= pitcher.ip_162 %> IPs</td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/pitchers/new.html.erb
<h1>New Pitcher</h1>

<%= render 'form', pitcher: @pitcher %>

<%= link_to 'Back', pitchers_path %>

app/views/pitchers/show.html.erb
<p id="notice"><%= notice %></p>

  <h1><div class=""></div><%= @pitcher.throws %>HP - <%= @pitcher.fname %> <%= @pitcher.lname %> (<%= @pitcher.season %>)</h1>

  <p><%= @pitcher.franchise %> bats: <%= @pitcher.bats %>, throws: <%= @pitcher.throws %></p>

  <div class="card text-white bg-primary mb-3" style="max-width: 20rem;">
  <div class="card-header">Basic Stats</div>
  <div class="card-body">
    <p class="card-text">IP per 162</p>
    <h4 class="card-title"><%= @pitcher.ip_162 %></h4>
    <p class="card-text">ERC#</p>
    <h4 class="card-title"><%= @pitcher.erc_norm %></h4>
    <p class="card-text">WHIP#</p>
    <h4 class="card-title"><%= @pitcher.whip_norm %></h4>
  </div>

  <div class="card-header">Fatigue</div>
  <p class="card-text">Max Pitches per Inning</p>
  <h4 class="card-title"><%= pitches_per_inning(@pitcher) %></h4>
  <p class="card-text">Max Pitches Total</p>
  <h4 class="card-title"><%= pitches_max(@pitcher) %></h4>


  <p class="card-text">Pitches/game - Starter - 4M rotation </p>
  <h4 class="card-title"><%= (pitches_max(@pitcher)/40.5).round(2) %></h4>
  <p class="card-text">Pitches/game - Starter - 3M rotation </p>
  <h4 class="card-title"><%= (pitches_max(@pitcher)/54).round(2) %></h4>
  <p class="card-text">Pitches/game - Starter - 2M rotation </p>
  <h4 class="card-title"><%= (pitches_max(@pitcher)/81).round(2) %></h4>


</div>

  <% @pitcher.attributes.each do |name, value| %>
       <%= name %>: <%= value %><br />
  <% end %>

<p>
<%= link_to 'Edit', edit_pitcher_path(@pitcher) %> |
<%= link_to 'Back', pitchers_path %>

app/views/search/index.html.erb
hey there